_target_: innofw.core.datamodules.lightning_datamodules.segmentation_dir.DirSegmentationLightningDataModule
channels_num: 1
date_time: 30.09.2022
description: stroke segmentation dataset
markup_info: segmentation masks
name: UW-Madison dataset
task:
  - multiclass-image-segmentation

test:
  source: ./data/organs/test
  # target:
train:
  source: ./data/organs/train
  # target: