defaults:
    - preprocessing:
        - standard_images
    - combined:
        - none
    - position:
        - random_resized_crop
        - flip
        - rotate90
        - transpose
        - grid_distortion
    - color:
        - random_gamma
        - blur
    - postprocessing:


# position:
#     rotate90:
#         p: 0.1