defaults:
  - _self_
  - datasets:
  - models:
  - trainer: auto
  - metrics: auto
  - losses: auto
  - optimizers: auto
  - schedulers: auto
  - augmentations: none
  - loggings: auto
  - callbacks: auto
  - initializations:
  - experiments: ???
  - clear_ml: enabled
  - override hydra/job_logging: disabled
#  - override hydra/job_logging: custom

project: ???
task: ???
random_seed:
epochs:
batch_size:
weights_path:
weights_freq:
ckpt_path:
stop_param:
experiment_name:

accelerator: cpu
#devices: 1
#gpus: 1
