task:
  - all

implementations:
  torch:
    CosineAnnealingWarmRestarts:
      object:
        _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
        T_0: 10
        T_mult: 1
        eta_min: 3e-6
