task:
  - all

implementations:
  torch:
    CosineAnnealingWarmRestarts:
      function:
        _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
        T_0: 30
        T_mult: 1
        eta_min: 3e-6