task:
  - all

implementations:
  torch:
    Custom:
      function:
        _target_: torch.optim.lr_scheduler.MultiStepLR
        milestones:
          - 30
          - 80
        gamma: 0.1
        last_epoch: -1
        verbose: False
