_target_: innofw.core.datamodules.lightning_datamodules.semantic_segmentation.tiff_dm.SegmentationDM
# ${.root}
train:
  source: /mnt/nvmestorage/qb/data_n_weights/linear-road-bin-seg-oftp/200323/processed/2023-03-21-2048-merged-with-old/train

test:
  source: /mnt/nvmestorage/qb/data_n_weights/linear-road-bin-seg-oftp/301122/processed/070123-167folders-2048/

# weights_csv_path: /mnt/nvmestorage/qb/data_n_weights/linear-road-bin-seg-oftp/301122/processed/070123-167folders-2048/weights.csv

num_workers: 32
batch_size: 16
channels: 3

name: something
task: image-segmentation
description: some
markup_info: some
date_time: some