name: Segmentation
description: 0.4 * focal_loss + 0.8 * dice_loss + surface_loss 
task:
  - image-segmentation

implementations:
  torch:
    DiceLoss:
      weight: 0.8
      object:
        _target_: innofw.core.losses.dice_loss_old.DiceLoss
        gamma: 1
    FocalLoss:
      weight: 0.4
      object:
        _target_: innofw.core.losses.focal_loss_old.FocalLoss
        gamma: 2 
    SurfaceLoss:
      weight: 1
      object:
        _target_: innofw.core.losses.surface_loss_old.SurfaceLoss
        activation: sigmoid